--- #YAML:1.0
name:               POEx-IKC-Queue
version:            0.0001
abstract:           IKC Queue implementation
author:
    - Philip Gwyn <gwyn -at- cpan.org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:                  1.28
    POE::Component::IKC:  0.22
    POE::Session::PlainCall:  0.02
    POEx::IKC::Connection:  0
    POEx::URI:            0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
